[build]
  command = "npm ci && npm run build"
  base = "prompt-orchestrator-frontend"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"